# NickSoldin configuration

distance-limit:
  enabled: true
  radius: 5

world-colors:
  enabled: true
  overworld: WHITE
  nether: RED
  end: LIGHT_PURPLE

# How often (ticks) to recheck visibility for stationary players (0 = disable task)
visibility:
  periodic-check-ticks: 10
